apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: perfscale-demo-app-pipelinerun-
spec:
  serviceAccountName: perfscale-demo-app-pipeline-sa
  pipelineRef:
    name: perfscale-demo-app-pipeline
  params: []
    ###- name: IMAGE
    ###  value: joeshiett/nodejs-app
    ###- name: TAG
    ###  value: latest
  workspaces:
    - name: linked-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
