---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-run-id
spec:
  results:
    - name: run-id
  steps:
    - name: get-run-id
      image: quay.io/jhutar/opl
      script: |
        #!/usr/bin/env bash
        date --utc -Ins | sed -e 's/[^a-zA-Z0-9_-]/_/g' -e 's/_00_00$//' | tr -d '\n' > $(results.run-id.path)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: opl-cli
spec:
  workspaces:
    - name: main-dir
      description: Volume with data you want to work with.
  params:
    - name: script
      description: The OPL CLI script to run
      type: string
      default: "status_data.py -h"
  steps:
    - name: opl-cli
      image: quay.io/jhutar/opl
      workingDir: $(workspaces.main-dir.path)
      script: $(params.script)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: perfscale-demo-app-pipeline
spec:
  params: []
  workspaces:
    - name: linked-workspace
    - name: results-ssh-credentials
  tasks:
    - name: get-run-id
      taskRef:
        name: get-run-id

    - name: fetch-repository-tools
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: linked-workspace
      params:
        - name: url
          value: https://github.com/jhutar/my-tekton-perfscale-experiment
        - name: subdirectory
          value: "my-tekton-perfscale-experiment"
        - name: deleteExisting
          value: "true"

    - name: fetch-repository-app
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: linked-workspace
      params:
        - name: url
          value: https://github.com/jhutar/perfscale-demo-app
        - name: subdirectory
          value: "perfscale-demo-app"
        - name: deleteExisting
          value: "true"

    - name: fetch-repository-results
      taskRef:
        name: git-cli
      params:
        - name: GIT_USER_EMAIL
          value: jhutar@redhat.com
        - name: GIT_USER_NAME
          value: Jan Hutar
        - name: GIT_SCRIPT
          value: |
            git clone git@github.com:jhutar/my-tekton-perfscale-experiment-results.git
      workspaces:
        - name: ssh-directory
          workspace: results-ssh-credentials
        - name: source
          workspace: linked-workspace

    - name: create-deployment
      taskRef:
        name: kubernetes-actions
      runAfter:
        - fetch-repository-tools
      params:
        - name: script
          value: |
            kubectl apply --filename my-tekton-perfscale-experiment/perfscale-demo-app-deploy.yaml
            kubectl rollout status deployment/postgresql
            kubectl rollout status deployment/perfscale-demo-app
      workspaces:
        - name: manifest-dir
          workspace: linked-workspace

    - name: create-test-data
      taskRef:
        name: kubernetes-actions
      runAfter:
        - create-deployment
      params:
        - name: script
          value: |
            set -x
            pod=$( kubectl get pods --no-headers -l app=perfscale-demo-app -o custom-columns=":metadata.name" )
            kubectl exec "pod/$pod" -- bash -c "export FLASK_APP=myapp.py; flask test-data"

    - name: run-test
      taskRef:
        name: opl-cli
      runAfter:
        - create-test-data
        - fetch-repository-app
      params:
        - name: script
          value: |
            set -x
            export PYTHONPATH=$( pwd )/perfscale-demo-app/
            export STATUS_DATA_FILE=status-data.json
            my-tekton-perfscale-experiment/test-with-opl.py --locust-local-runner --locust-num-clients 10 --locust-hatch-rate 10 --locust-host http://perfscale-demo-service:80 --test-duration 100 || true
      workspaces:
        - name: main-dir
          workspace: linked-workspace

    - name: determine-results
      taskRef:
        name: opl-cli
      runAfter:
        - run-test
        - fetch-repository-results
      params:
        - name: script
          value: |
            set -x
            status_data.py --status-data-file status-data.json --set id=$(tasks.get-run-id.results.run-id)
            pass_or_fail.py --config my-tekton-perfscale-experiment/investigator_config.yaml --current-file status-data.json -d || true
      workspaces:
        - name: main-dir
          workspace: linked-workspace

    - name: push-results
      taskRef:
        name: git-cli
      runAfter:
        - determine-results
      params:
        - name: GIT_USER_EMAIL
          value: jhutar@redhat.com
        - name: GIT_USER_NAME
          value: Jan Hutar
        - name: GIT_SCRIPT
          value: |
            mv status-data.json my-tekton-perfscale-experiment-results/status-data-$(tasks.get-run-id.results.run-id).json
            cd my-tekton-perfscale-experiment-results/
            git add status-data-$(tasks.get-run-id.results.run-id).json
            git add decisions.csv
            git commit -m "Adding result $(tasks.get-run-id.results.run-id)"
            git pull --rebase
            git push
      workspaces:
        - name: ssh-directory
          workspace: results-ssh-credentials
        - name: source
          workspace: linked-workspace

    - name: delete-deployment
      taskRef:
        name: kubernetes-actions
      runAfter:
        - push-results
      params:
        - name: script
          value: |
            kubectl delete --filename my-tekton-perfscale-experiment/perfscale-demo-app-deploy.yaml
            # Old kubectl in kubernetes-actions? https://github.com/kubernetes/kubernetes/issues/96676
            kubectl wait --for=delete deployment/postgresql || true
            kubectl wait --for=delete deployment/perfscale-demo-app || true
      workspaces:
        - name: manifest-dir
          workspace: linked-workspace
